# Generated by Django 5.2.1 on 2025-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uniqueness', models.TextField()),
                ('Powermeter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Counter', models.PositiveIntegerField(verbose_name='Контра')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appearance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ManyToManyField(to='tralelotrala.category')),
            ],
        ),
    ]
