# Generated by Django 5.2.1 on 2025-05-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralelotrala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Counter',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='Powermeter',
            new_name='powermeter',
        ),
    ]
