# Generated by Django 5.2.1 on 2025-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralelotrala', '0002_rename_counter_animal_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='appearance',
            field=models.DateField(verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='powermeter',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сила(вимірюється кількістю знищеного мирного населення в Палестині)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розміри(В Метрах)'),
        ),
    ]
